"""Items shown in the UI while new source integrations are being prepared."""

FRONTEND_ITEMS = [
    {
        "source_ref": "campus_police:20260607-01",
        "title": "黑色 iPhone 15 手機",
        "category": "電子產品",
        "location": "新生南路三段校門附近",
        "found_at": "2026-06-07T11:20:00",
        "description": "黑色 iPhone 15，透明保護殼，背面夾有一張藍色貼紙。",
        "source_name": "駐警隊",
        "source_type": "police",
        "source_url": "",
    },
    {
        "source_ref": "campus_police:20260606-02",
        "title": "深咖啡色皮夾",
        "category": "現金/錢包",
        "location": "管理學院一號館前",
        "found_at": "2026-06-06T17:45:00",
        "description": "深咖啡色短夾，內有數張卡片，已送交駐警隊保管。",
        "source_name": "駐警隊",
        "source_type": "police",
        "source_url": "",
    },
    {
        "source_ref": "campus_police:20260606-03",
        "title": "台大學生證",
        "category": "證件/卡片",
        "location": "普通教學館一樓走廊",
        "found_at": "2026-06-06T14:10:00",
        "description": "一張台大學生證，於普通教學館一樓飲水機旁拾獲。",
        "source_name": "駐警隊",
        "source_type": "police",
        "source_url": "",
    },
    {
        "source_ref": "campus_police:20260605-04",
        "title": "銀色鑰匙一串",
        "category": "鑰匙",
        "location": "綜合體育館一樓",
        "found_at": "2026-06-05T20:30:00",
        "description": "三支銀色鑰匙，附有黑色圓形鑰匙圈。",
        "source_name": "駐警隊",
        "source_type": "police",
        "source_url": "",
    },
    {
        "source_ref": "fb_exchange:20260607-01",
        "title": "白色 AirPods Pro 耳機",
        "category": "電子產品",
        "location": "第二學生活動中心三樓",
        "found_at": "2026-06-07T12:35:00",
        "description": "在二活三樓座位區撿到白色 AirPods Pro 充電盒，外殼有灰色保護套。",
        "source_name": "FB交流版",
        "source_type": "facebook",
        "source_url": "https://www.facebook.com/",
    },
    {
        "source_ref": "fb_exchange:20260607-02",
        "title": "淺藍色折疊雨傘",
        "category": "雨傘",
        "location": "第一學生活動中心一樓",
        "found_at": "2026-06-07T09:15:00",
        "description": "活大一樓靠近影印店的位置撿到一把淺藍色折疊傘，傘柄有白色掛繩。",
        "source_name": "FB交流版",
        "source_type": "facebook",
        "source_url": "https://www.facebook.com/",
    },
    {
        "source_ref": "fb_exchange:20260606-03",
        "title": "黑色 Nike 後背包",
        "category": "包包",
        "location": "總圖書館前廣場",
        "found_at": "2026-06-06T19:05:00",
        "description": "黑色 Nike 後背包，側邊有水壺袋，拉鍊上掛著紅色吊飾。",
        "source_name": "FB交流版",
        "source_type": "facebook",
        "source_url": "https://www.facebook.com/",
    },
    {
        "source_ref": "fb_exchange:20260605-04",
        "title": "粉紅色保溫杯",
        "category": "水壺/餐具",
        "location": "社會科學院圖書館",
        "found_at": "2026-06-05T16:40:00",
        "description": "粉紅色保溫杯，杯身有白色英文字樣，在社科院圖書館座位區拾獲。",
        "source_name": "FB交流版",
        "source_type": "facebook",
        "source_url": "https://www.facebook.com/",
    },
]
