import os
import sys
import pandas as pd
from pathlib import Path
from sqlalchemy.exc import IntegrityError

# Fix python paths so the script can execute from root directory context
sys.path.append(str(Path(__file__).parent.parent))

from core import create_app
from core.extensions import db
from core.models import LostItem

def seed_database(csv_filepath: str, source_name: str):
    app = create_app()
    
    # Load the CSV generated by your scraper prototype
    if not os.path.exists(csv_filepath):
        print(f"Error: Could not find {csv_filepath}")
        return

    df = pd.read_csv(csv_filepath, encoding="utf-8-sig")
    print(f"Found {len(df)} records in CSV. Beginning import...")

    with app.app_context():
        success_count = 0
        skip_count = 0

        for index, row in df.iterrows():
            # Map the CSV headers to your Postgres schema
            # We omit 'id' because Postgres will auto-increment it
            item = LostItem(
                source_system=source_name,
                original_id=str(row['編號']),
                found_date=str(row['拾獲日期']),
                location=str(row['拾獲地點']) if pd.notna(row['拾獲地點']) else None,
                description=str(row['外觀描述']) if pd.notna(row['外觀描述']) else None,
                category=str(row['物品分類']) if pd.notna(row['物品分類']) else None,
                storage_place=str(row['存放地點']) if pd.notna(row['存放地點']) else None
            )

            db.session.add(item)
            
            try:
                # Commit row by row (or in batches) to handle unique constraints
                db.session.commit()
                success_count += 1
            except IntegrityError:
                # If the script tries to add a duplicate (source_system + original_id), skip it safely
                db.session.rollback()
                skip_count += 1

        print(f"Seed complete! Successfully inserted {success_count} records.")
        if skip_count > 0:
            print(f"Skipped {skip_count} duplicates based on unique constraints.")

if __name__ == "__main__":
    # Ensure you place your training_data.csv in a folder like 'seed_data/'
    TARGET_CSV = "scripts/scrapers/seed_data/lib_seed_data.csv"
    
    # Define the exact source system name that your Edge Function will use later
    TARGET_SOURCE_SYSTEM = "school_libraries" 
    
    seed_database(TARGET_CSV, TARGET_SOURCE_SYSTEM)
    
